### ISSUE TITLE
Feature request: guaranteed exact result

### ISSUE THREAD

**Issue by mdpkh** [BreadMakesYouFull/baseconvert#3]
Since this module only deals in rational numbers, and positional representation of all rational numbers either terminate or repeat with a finite period, it ought to be possible to specify an argument like exact=True which forces the base convert routine to generate as many digits as necessary to return a mathematically correct result. This will require either changing how repeating digits are found _(integrating that process into fractional_base())_, or generating at least max_period * min_repeat _(where max_period can be calculated from the input base, the number of nonrepeating fractional digits of input, and the number of repeating fractional digits of input)_ before find_recurring() is called.

**Comment by squdle** [comment]
Attempted this approach, but struggled to find a complete solution.

Have gone a middle ground where you can set "max_depth" to 0, or "exact" to True, and optionally set MAX_DEPTH on module to as high as required
